// SPDX-License-Identifier: AGPL-3.0-or-later
// src/votingPilot/events.js
export const VOTING_PILOT_EVENTS = Object.freeze({
  CONSENT_ACCEPTED: "VOTING_PILOT_CONSENT_ACCEPTED",
  STARTED: "VOTING_PILOT_STARTED",
  SUBMITTED: "VOTING_PILOT_SUBMITTED",
  WITHDRAWN: "VOTING_PILOT_WITHDRAWN",
  REPORT_EXPORTED: "VOTING_PILOT_REPORT_EXPORTED",
  BALLOT_FIELD_REJECTED: "BALLOT_FIELD_REJECTED",
});
