#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Stage 5Q — static census driver.
//
// The rule lives in core/censusStatic.mjs and is pure over an injected file list. This file does the
// I/O: walk the eight closure roots, read bytes, hand them over, print or write the result.
//
//   --format=summary   counts by root and category (the diagnostic)
//   --format=json      the full member list
//   --out <path>       write JSON to a file
//
// The counts this prints are a DIAGNOSTIC, never a target (Annex A1.4). If the output happens to
// match a remembered number, that is evidence R8 did not fire, not evidence the census is right.

import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { staticCensus, rootFor } from "../core/censusStatic.mjs";
import { CLOSURE_ROOTS } from "../core/constants.mjs";
import { skeletonFor, ROLE_RULES, validateRuleTable } from "../core/roleAssignment.mjs";

const REPO = process.cwd();
const EXTS = new Set([".mjs", ".js", ".py", ".lean", ".sh"]);

const ROOT_DIRS = [
  "tools/simurgh-attestation",
  "tests/e2e/llmShield",
  "tests/unit/llmShield",
  "proofs",
  "scripts",
];

function walk(dir, acc = []) {
  if (!existsSync(dir)) return acc;
  for (const name of readdirSync(dir)) {
    if (name === "node_modules" || name === ".git") continue;
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, acc);
    else {
      const ext = name.slice(name.lastIndexOf("."));
      if (EXTS.has(ext)) acc.push(relative(REPO, full).split(sep).join("/"));
    }
  }
  return acc;
}

function collectFiles() {
  const paths = [];
  for (const d of ROOT_DIRS) paths.push(...walk(join(REPO, d)));
  // Only files that a closure root claims. Everything else is outside the universe by definition,
  // and quietly including it would make the closure describe more than the spec says it does.
  return paths
    .filter((p) => rootFor(p) !== null)
    .sort()
    .map((path) => ({ path, bytes: readFileSync(join(REPO, path)) }));
}

function main(argv) {
  const format = (argv.find((a) => a.startsWith("--format=")) ?? "--format=summary").split("=")[1];
  const outIdx = argv.indexOf("--out");
  const out = outIdx >= 0 ? argv[outIdx + 1] : null;

  const files = collectFiles();
  const census = staticCensus({ files });

  // --emit-role-skeleton: generate roles/stage5-roles.json (Task 6, gauntlet P1-13).
  //
  // The skeleton is GENERATED and then reviewed; it is never hand-authored from nothing. For ~2,500
  // members the totality rules are mechanical — exactly one role per member, no unknown ids, no
  // duplicates, no unassigned members — and a hand-written file is precisely where an omission
  // hides. Every entry records the rule that produced it.
  if (argv.includes("--emit-role-skeleton")) {
    const ruleCheck = validateRuleTable(ROLE_RULES);
    if (!ruleCheck.ok) {
      console.log("REFUSING to emit: the rule table is unsound");
      for (const p of ruleCheck.problems) console.log(`    ${p.rule_id}: ${p.reason}`);
      return 1;
    }
    const assignments = census.members.map(skeletonFor);
    const byRole = {};
    const byBasis = {};
    for (const a of assignments) {
      byRole[a.security_role] = (byRole[a.security_role] ?? 0) + 1;
      byBasis[a.basis] = (byBasis[a.basis] ?? 0) + 1;
    }
    const needsReview = assignments.filter((a) => a.needs_review);
    const payload = {
      schema: "simurgh.vsr.role-assignment.v1",
      note:
        "GENERATED by measureStaticCensus --emit-role-skeleton, then reviewed. An ARRAY, not a " +
        "map: a JSON object keyed by function_id would let JSON.parse silently keep the last of " +
        "two contradictory assignments, and a duplicate must be visible to the checker.",
      generated_from: { parser: "acorn@8.17.0", member_count: census.members.length },
      rule_table: ROLE_RULES.map((r) => ({ id: r.id, role: r.role, rationale: r.rationale })),
      counts_by_role: byRole,
      counts_by_basis: byBasis,
      assignments,
    };
    const json = `${JSON.stringify(payload, null, 2)}\n`;
    const target = out ?? "tools/simurgh-attestation/stage5q/roles/stage5-roles.json";
    writeFileSync(target, json);
    console.log(`Stage 5Q role skeleton -> ${target}`);
    console.log(`  members            : ${assignments.length}`);
    console.log("  by role            :", JSON.stringify(byRole));
    console.log("  by basis           :", JSON.stringify(byBasis));
    console.log(`  needs_review       : ${needsReview.length}`);
    for (const a of needsReview.slice(0, 20)) console.log(`      ? ${a.function_id}`);
    if (needsReview.length > 20) console.log(`      … and ${needsReview.length - 20} more`);
    // A needs_review entry blocks Task 6. The generator reports it and exits non-zero rather than
    // writing a file that reads complete.
    return needsReview.length > 0 ? 1 : 0;
  }

  const byRoot = {};
  const byCategory = {};
  const byExtraction = {};
  for (const m of census.members) {
    byRoot[m.root] = (byRoot[m.root] ?? 0) + 1;
    byCategory[m.category] = (byCategory[m.category] ?? 0) + 1;
    byExtraction[m.extraction_method] = (byExtraction[m.extraction_method] ?? 0) + 1;
  }

  if (format === "json" || out) {
    const payload = {
      parser: "acorn@8.17.0",
      roots: CLOSURE_ROOTS.map((r) => r.id),
      file_count: files.length,
      member_count: census.members.length,
      edge_count: census.edges.length,
      // The graph counts travel WITH the census. `resolved_edges` is the number that decides
      // whether every reachability question is being answered or merely asked: at zero, each one
      // passes vacuously. It was zero once, and the §2.4 role rule certified an empty graph.
      graph: census.graph,
      members: census.members,
      edges: census.edges,
      parse_errors: census.parseErrors,
      duplicates: census.duplicates,
    };
    const json = JSON.stringify(payload, null, 2);
    if (out) writeFileSync(out, `${json}\n`);
    if (format === "json" && !out) console.log(json);
  }

  if (format === "summary") {
    console.log("Stage 5Q static census — DIAGNOSTIC, not a target (Annex A1.4)");
    console.log(`  files walked        : ${files.length}`);
    console.log(`  members             : ${census.members.length}`);
    console.log(`  edges               : ${census.edges.length}`);
    console.log(
      `  resolved edges      : ${census.graph.resolved_edges}` +
        `  (cross-module ${census.graph.linked_cross_module}, ` +
        `unresolved ${census.graph.unresolved_edges}, ` +
        `unattributed ${census.graph.unattributed_calls})`
    );
    console.log("  by root             :", JSON.stringify(byRoot));
    console.log("  by extraction       :", JSON.stringify(byExtraction));
    console.log("  by category         :");
    for (const [k, v] of Object.entries(byCategory).sort((a, b) => b[1] - a[1])) {
      console.log(`      ${String(v).padStart(6)}  ${k}`);
    }
    console.log(`  parse errors        : ${census.parseErrors.length}`);
    console.log(`  duplicate ids       : ${census.duplicates.length}`);
  }

  // Parse errors and duplicates are precommit_blockers (second gauntlet B4): they block Task 8,
  // and they are not "findings" while no ledger exists.
  const blockers = census.parseErrors.length + census.duplicates.length;
  if (blockers > 0) {
    console.log(
      `\n  PRECOMMIT BLOCKERS: ${blockers} — Task 8 must not run until these are resolved`
    );
    for (const e of census.parseErrors.slice(0, 10))
      console.log(`    parse: ${e.path}: ${e.message}`);
    for (const d of census.duplicates.slice(0, 10)) console.log(`    duplicate id: ${d}`);
  }
  return blockers > 0 ? 1 : 0;
}

// THE MAIN GUARD. Without it, `await import(...)` of this file RUNS it — which is finding 5Q-F003,
// the defect this stage froze against Stage 5M, committed here in our own drivers. Ten of them did
// it, and the K7 export census is what found them: it could not enumerate a module that exits
// during enumeration.
if (import.meta.url === `file://${process.argv[1]}`) {
  process.exit(main(process.argv.slice(2)));
}
