// SPDX-License-Identifier: AGPL-3.0-or-later
// Stage 5O — A27's four byte maxima. The script must PROVE its maxima, not print them.
//
// These assertions are the authority from which A27 receives its numbers. No limit is hand-edited
// after generation; if a schema changes, this test moves the number or fails.
import { test } from "node:test";
import assert from "node:assert/strict";
import { canonicalJson } from "../../../../tools/simurgh-attestation/stage4m/core/canonical.mjs";
import { decodeDigestToken } from "../../../../tools/simurgh-attestation/stage5o/core/digestTokenCodec.mjs";
import {
  MAX_BEACON_SUFFIX_HEADERS_V1,
  MAX_SELECTED_INDICES_V1,
} from "../../../../tools/simurgh-attestation/stage5o/core/constants.mjs";
import {
  generateMaxima,
  measure,
  maximalBeaconSuffixArtifact,
  maximalOrderedSelectedIndicesArtifact,
  maximalChallengeRecord,
} from "../../../../tools/simurgh-attestation/stage5o/node/measureChallengeMaxima.mjs";
import {
  requireCanonicalBytes,
  checkBeaconSuffixArtifactShape,
  checkOrderedSelectedIndicesArtifactShape,
  checkChallengeRecordShape,
} from "../../../../tools/simurgh-attestation/stage5o/core/challengeArtifactShape.mjs";

/** The negative-fixture law, carried forward from the codec vectors. */
function assertNegativeVector({ name, valid, mutated, accept, property, propertyName }) {
  assert.notEqual(
    canonicalJson(mutated),
    canonicalJson(valid),
    `${name}: PREMISE FAILED — the mutation did not change the input`
  );
  assert.doesNotThrow(
    () => accept(valid),
    `${name}: PREMISE FAILED — the baseline is not accepted`
  );
  if (property) {
    assert.ok(
      property(mutated),
      `${name}: PREMISE FAILED — mutant lacks the property "${propertyName}"`
    );
  }
  assert.throws(() => accept(mutated), `${name}: the mutated input must be REJECT`);
}

test("maxima: the generated objects have the exact required shape", () => {
  const s = maximalBeaconSuffixArtifact();
  assert.equal(s.headers.length, MAX_BEACON_SUFFIX_HEADERS_V1);
  assert.equal(s.headers.length, 2016);

  const i = maximalOrderedSelectedIndicesArtifact();
  assert.equal(i.indices.length, MAX_SELECTED_INDICES_V1);
  assert.equal(i.indices.length, 65536);
  assert.equal(i.indices[0], "0");
  assert.equal(i.indices[i.indices.length - 1], "65535");
});

test("maxima: every digest token in every generated object decodes to exactly 32 bytes", () => {
  const objs = [
    maximalBeaconSuffixArtifact(),
    maximalOrderedSelectedIndicesArtifact(),
    maximalChallengeRecord(),
  ];
  let n = 0;
  for (const o of objs) {
    for (const [k, v] of Object.entries(o)) {
      if (k.endsWith("_digest")) {
        assert.equal(decodeDigestToken(v).length, 32, `${k} must decode to 32 bytes`);
        assert.equal(v.length, 71, `${k} must be a 71-char token`);
        n++;
      }
    }
  }
  assert.equal(n, 9, "expected 9 digest fields across the three artifacts");
});

test("maxima: all generated bytes are canonical round trips", () => {
  for (const o of [
    maximalBeaconSuffixArtifact(),
    maximalOrderedSelectedIndicesArtifact(),
    maximalChallengeRecord(),
  ]) {
    const raw = canonicalJson(o);
    assert.doesNotThrow(() => requireCanonicalBytes(raw), "generated bytes must be canonical");
    assert.equal(canonicalJson(JSON.parse(raw)), raw);
  }
});

test("maxima: the generated objects pass the shape rules", () => {
  assert.doesNotThrow(() => checkBeaconSuffixArtifactShape(maximalBeaconSuffixArtifact()));
  assert.doesNotThrow(() =>
    checkOrderedSelectedIndicesArtifactShape(maximalOrderedSelectedIndicesArtifact(), 65536)
  );
  assert.doesNotThrow(() => checkChallengeRecordShape(maximalChallengeRecord()));
});

test("maxima: the four A27 numbers, generated and exact", () => {
  const m = generateMaxima();
  // Pinned to the generated values. If a schema changes, this fails and A27's numbers move --
  // which is the point: the script is the authority, not a remembered constant.
  assert.equal(m.MAX_BEACON_SUFFIX_ARTIFACT_BYTES_V1, 328873);
  assert.equal(m.MAX_SELECTED_INDICES_ARTIFACT_BYTES_V1, 513335);
  assert.equal(m.MAX_CHALLENGE_RECORD_BYTES_V1, 661);
  assert.equal(m.MAX_CHALLENGE_PACKAGE_BYTES_V1, 842869);
});

test("maxima: package total is the EXACT arithmetic sum — no wrapper, no margin", () => {
  const m = generateMaxima();
  assert.equal(
    m.MAX_CHALLENGE_PACKAGE_BYTES_V1,
    m.MAX_BEACON_SUFFIX_ARTIFACT_BYTES_V1 +
      m.MAX_SELECTED_INDICES_ARTIFACT_BYTES_V1 +
      m.MAX_CHALLENGE_RECORD_BYTES_V1,
    "there is no package object, so no delimiter/array/newline/transport bytes exist to add"
  );
});

test("maxima: each generated object measures exactly its own limit", () => {
  const m = generateMaxima();
  assert.equal(measure(maximalBeaconSuffixArtifact()), m.MAX_BEACON_SUFFIX_ARTIFACT_BYTES_V1);
  assert.equal(
    measure(maximalOrderedSelectedIndicesArtifact()),
    m.MAX_SELECTED_INDICES_ARTIFACT_BYTES_V1
  );
  assert.equal(measure(maximalChallengeRecord()), m.MAX_CHALLENGE_RECORD_BYTES_V1);
});

test("boundary: 2017 headers REJECT", () => {
  const valid = maximalBeaconSuffixArtifact();
  const over = maximalBeaconSuffixArtifact();
  over.headers = [...over.headers, "a".repeat(160)];
  assertNegativeVector({
    name: "headers_2017",
    valid,
    mutated: over,
    accept: checkBeaconSuffixArtifactShape,
    property: (o) => o.headers.length === 2017,
    propertyName: "header_count == 2017",
  });
});

test("boundary: 65537 indices REJECT", () => {
  const valid = maximalOrderedSelectedIndicesArtifact();
  const over = maximalOrderedSelectedIndicesArtifact();
  over.indices = [...over.indices, "65536"];
  assertNegativeVector({
    name: "indices_65537",
    valid,
    mutated: over,
    accept: (o) => checkOrderedSelectedIndicesArtifactShape(o, 65536),
    property: (o) => o.indices.length === 65537,
    propertyName: "index_count == 65537",
  });
});

test('boundary: leading-zero index "065535" REJECT', () => {
  const valid = maximalOrderedSelectedIndicesArtifact();
  const bad = maximalOrderedSelectedIndicesArtifact();
  bad.indices = [...bad.indices.slice(0, -1), "065535"];
  assertNegativeVector({
    name: "index_leading_zero",
    valid,
    mutated: bad,
    accept: (o) => checkOrderedSelectedIndicesArtifactShape(o, 65536),
    property: (o) => o.indices[o.indices.length - 1] === "065535",
    propertyName: "last index has a leading zero",
  });
});

test('boundary: out-of-universe index "65536" REJECT', () => {
  const valid = maximalOrderedSelectedIndicesArtifact();
  const bad = maximalOrderedSelectedIndicesArtifact();
  bad.indices = [...bad.indices.slice(0, -1), "65536"];
  assertNegativeVector({
    name: "index_out_of_universe",
    valid,
    mutated: bad,
    accept: (o) => checkOrderedSelectedIndicesArtifactShape(o, 65536),
    property: (o) => o.indices.includes("65536"),
    propertyName: "contains an index == N",
  });
});

test("boundary: uppercase digest token REJECT", () => {
  const valid = maximalChallengeRecord();
  const bad = maximalChallengeRecord();
  bad.beacon_suffix_digest = bad.beacon_suffix_digest.toUpperCase();
  assertNegativeVector({
    name: "uppercase_digest_token",
    valid,
    mutated: bad,
    accept: checkChallengeRecordShape,
    property: (o) => /[A-Z]/.test(o.beacon_suffix_digest),
    propertyName: "contains_uppercase_ascii",
  });
});

test("boundary: extra schema key REJECT", () => {
  const valid = maximalChallengeRecord();
  const bad = maximalChallengeRecord();
  bad.beacon_value = "sha256:" + "ab".repeat(32); // the field v4 deliberately removed
  assertNegativeVector({
    name: "extra_schema_key",
    valid,
    mutated: bad,
    accept: checkChallengeRecordShape,
    property: (o) => "beacon_value" in o,
    propertyName: "carries an extra key",
  });
});

test("boundary: noncanonical JSON byte encoding REJECT", () => {
  // A canonical-size limit is sound ONLY when canonical encoding is a condition of acceptance.
  // Each of these parses to the SAME object and is byte-wise noncanonical.
  const record = maximalChallengeRecord();
  const canonical = canonicalJson(record);
  assert.doesNotThrow(() => requireCanonicalBytes(canonical));

  const whitespace = JSON.stringify(JSON.parse(canonical), null, 2);
  const reordered = JSON.stringify(
    Object.fromEntries(Object.entries(JSON.parse(canonical)).reverse())
  );

  for (const [name, raw] of Object.entries({ whitespace, reordered })) {
    assert.notEqual(raw, canonical, `${name}: PREMISE FAILED — the mutation did not change bytes`);
    assert.deepEqual(JSON.parse(raw), JSON.parse(canonical), `${name}: premise — same object`);
    assert.throws(() => requireCanonicalBytes(raw), `${name} must REJECT`);
  }

  // and the attack this rule exists to stop: expansion under an aggregate limit
  assert.ok(
    Buffer.byteLength(whitespace, "utf8") > Buffer.byteLength(canonical, "utf8"),
    "premise: whitespace expansion is strictly larger than the canonical maximum"
  );
});
