export const EVENTS = Object.freeze({
  EXAM_STARTED: "EXAM_STARTED",
  PRIVACY_ACCEPTED: "PRIVACY_ACCEPTED",
  HELPER_CONNECTED: "HELPER_CONNECTED",
  HELPER_DISCONNECTED: "HELPER_DISCONNECTED",
  TELEMETRY_WINDOW_RECEIVED: "TELEMETRY_WINDOW_RECEIVED",
  FOCUS_LOSS: "FOCUS_LOSS",
  LONG_TIME_OFF_WINDOW: "LONG_TIME_OFF_WINDOW",
  BULK_PASTE: "BULK_PASTE",
  REPEATED_PASTE: "REPEATED_PASTE",
  ABNORMAL_WPM_SPIKE: "ABNORMAL_WPM_SPIKE",
  LONG_IDLE_GAP: "LONG_IDLE_GAP",
  CAPTURE_EXCLUDED_WINDOW: "CAPTURE_EXCLUDED_WINDOW",
  RISK_ESCALATED: "RISK_ESCALATED",
  RISK_DEESCALATED: "RISK_DEESCALATED",
  SESSION_RECONNECTED: "SESSION_RECONNECTED",
  EXAM_SUBMITTED: "EXAM_SUBMITTED",
  REPORT_GENERATED: "REPORT_GENERATED",
  AUDIT_VERIFIED: "AUDIT_VERIFIED",
  // Stage 2 integrity proof events
  INTEGRITY_PROOF_RECEIVED: "INTEGRITY_PROOF_RECEIVED",
  INTEGRITY_PROOF_REJECTED: "INTEGRITY_PROOF_REJECTED",
  // Defined for Stage 2.x staleness checker. Not emitted by Stage 2.1.
  INTEGRITY_NODE_STALE: "INTEGRITY_NODE_STALE",
  // Stage 2.2 — pairing events
  INTEGRITY_PAIRING_CHALLENGE_CREATED: "INTEGRITY_PAIRING_CHALLENGE_CREATED",
  INTEGRITY_NODE_PAIRED: "INTEGRITY_NODE_PAIRED",
  INTEGRITY_PAIRING_REJECTED: "INTEGRITY_PAIRING_REJECTED",
  // Stage 2.3 — localhost daemon events
  DAEMON_DISCOVERED: "DAEMON_DISCOVERED",
  DAEMON_MISSING: "DAEMON_MISSING",
  DAEMON_PAIRING_CHALLENGE_ISSUED: "DAEMON_PAIRING_CHALLENGE_ISSUED",
  DAEMON_PAIRED: "DAEMON_PAIRED",
  DAEMON_SESSION_STARTED: "DAEMON_SESSION_STARTED",
  DAEMON_PROOF_VERIFIED: "DAEMON_PROOF_VERIFIED",
  DAEMON_PROOF_REJECTED: "DAEMON_PROOF_REJECTED",
  DAEMON_STALE: "DAEMON_STALE",
  DAEMON_UNTRUSTED: "DAEMON_UNTRUSTED",
  DAEMON_SESSION_ENDED: "DAEMON_SESSION_ENDED",
  DEVICE_RISK_ESCALATED: "DEVICE_RISK_ESCALATED",
});

export function createEvent(sessionId, type, detail = {}) {
  return { sessionId, type, detail, ts: Date.now() };
}

export function eventTimeline() {
  const store = new Map();

  return {
    add(sessionId, type, detail = {}) {
      if (!store.has(sessionId)) store.set(sessionId, []);
      store.get(sessionId).push(createEvent(sessionId, type, detail));
    },
    get(sessionId) {
      return [...(store.get(sessionId) ?? [])];
    },
    clear(sessionId) {
      store.delete(sessionId);
    },
  };
}
