export const DAEMON_EVENTS = Object.freeze({
  DAEMON_DISCOVERED: "DAEMON_DISCOVERED",
  DAEMON_MISSING: "DAEMON_MISSING",
  DAEMON_PAIRING_CHALLENGE_ISSUED: "DAEMON_PAIRING_CHALLENGE_ISSUED",
  DAEMON_PAIRED: "DAEMON_PAIRED",
  DAEMON_SESSION_STARTED: "DAEMON_SESSION_STARTED",
  DAEMON_PROOF_VERIFIED: "DAEMON_PROOF_VERIFIED",
  DAEMON_PROOF_REJECTED: "DAEMON_PROOF_REJECTED",
  DAEMON_STALE: "DAEMON_STALE",
  DAEMON_UNTRUSTED: "DAEMON_UNTRUSTED",
  DAEMON_SESSION_ENDED: "DAEMON_SESSION_ENDED",
  DEVICE_RISK_ESCALATED: "DEVICE_RISK_ESCALATED",
});
