// SPDX-License-Identifier: AGPL-3.0-or-later
// Stage 5O §12.6 — the lane enum and the salt profile.
//
// The accepted lane enum has exactly TWO values. `dishonest_producer_fixture` is a TEST-CORPUS class,
// never a lane: a producer must never be able to declare itself into a fixture lane and thereby
// select weaker validation.
//
// Lane A salts are deterministic and therefore provide NO hiding — they are a public function of a
// public key, so anyone who can guess a section's content can confirm the guess. Lane A is binding
// and byte-stable CI evidence, not confidentiality (see `not_proof_of_redacted_section_
// confidentiality_in_lane_a`). Lane B salts must be independently generated and must NEVER be
// derived from the Bitcoin beacon, from `challenge_seed`, or from any public package field.
//
// What this check CAN prove: the exact salt key set, grammar and width, uniqueness, Lane A
// deterministic equality, and the absence of a declared deterministic fallback. What it CANNOT prove
// from bytes: true entropy, actual CSPRNG origin, absence of collusion, or future salt secrecy —
// hence the signed `not_proof_of_package_capsule_salt_entropy`.
import { deterministicSalt } from "../../stage4t/core/viewCore.mjs";

export const LANES = Object.freeze({
  A: "lane_a_deterministic_fixture",
  B: "lane_b_random_ceremony",
});
export const LANE_VALUES = Object.freeze([LANES.A, LANES.B]);

const HEX64 = /^[0-9a-f]{64}$/;

/** Validate the declared lane against the salt class actually in use. */
export function laneVerdict(lane, salts, mandatoryKeys) {
  if (!LANE_VALUES.includes(lane)) return { ok: false, detail: "unknown_lane" };
  if (salts === null || typeof salts !== "object") return { ok: false, detail: "salts_shape" };

  const keys = Object.keys(salts).sort();
  const want = [...mandatoryKeys].sort();
  if (keys.length !== want.length || keys.some((k, i) => k !== want[i])) {
    return { ok: false, detail: "salt_key_census" };
  }
  for (const k of keys) {
    if (!HEX64.test(salts[k])) return { ok: false, detail: "salt_grammar" };
  }
  // 32 independently generated bytes per key: uniqueness is checkable from the bytes.
  if (new Set(Object.values(salts)).size !== keys.length) {
    return { ok: false, detail: "salt_not_unique" };
  }

  const deterministicEverywhere = keys.every((k) => salts[k] === deterministicSalt(k));
  if (lane === LANES.A) {
    // Lane A must BE the deterministic profile; anything else is a mislabelled ceremony.
    return deterministicEverywhere
      ? { ok: true }
      : { ok: false, detail: "lane_a_not_deterministic" };
  }
  // Lane B must not be the deterministic profile, in whole or in part: a single deterministic salt
  // silently removes hiding for that section while the package still claims a ceremony lane.
  for (const k of keys) {
    if (salts[k] === deterministicSalt(k))
      return { ok: false, detail: "lane_b_deterministic_salt" };
  }
  return { ok: true };
}
